# use version 3 of the docker compose syntax
version: '3'
services:
  # we named our first service 'web'
  web:
    # pass a hostname to the container (optinal)
    hostname: goodbytes3.local

    # build a custom image
    build:
      context: ./
      dockerfile: dockerfile

    # a name for easier reference
    image: goodbytes3.local

    # map host port 3001 to container port 80
    ports:
        - 3001:80

    # sets the working directory of the container that is created
    working_dir: /var/www/html/

    # volumes are like shared folders
    # container will see your local code changes
    volumes:
      - .:/var/www/html/

    # first load the 'db' service
    depends_on:
      - db

    # make 'db' a known service/host inside of 'web'
    # use this to make a mysql connection to host 'db'
    links:
      - db

  db:
    # use a default image
    image: mysql

    # again, port mapping
    # e.g. to use Sequel Pro on our mac
    ports:
      - 13306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    # the mysql image uses these to create database and users
    environment:
      MYSQL_ROOT_PASSWORD: something-secure-here
      MYSQL_DATABASE: bolt
      MYSQL_USER: bolt
      MYSQL_PASSWORD: something-secure-here
